-- =============================================================================
-- PARTE 39: Atualização do GGCON a partir da planilha "Controle de Processos -
-- SEI.xlsm" (aba SEI), versão mais recente enviada pelo usuário.
-- 1) INSERT: 29 movimentações novas desde a última importação (parte_37).
-- 2) UPDATE: 8 movimentações já importadas que mudaram de conteúdo — 5 são só
--    correção de acentuação corrompida na importação anterior (mesmo texto,
--    caracteres ilegíveis -> corretos) e 3 são atualizações reais feitas na
--    planilha (etapa/técnico/valor/data) que ainda não tinham uma linha nova.
-- Execute no SQL Editor do Supabase (primeiro o bloco INSERT, depois os UPDATE).
-- =============================================================================

INSERT INTO public.cgof_ggcon_processos (processo_sei, numero_demanda, data_entrada, data_recebimento, municipio, drs_unidade, coordenadoria, interessado, assunto, tipo, tecnico_responsavel, etapa, data_movimentacao, aguardando_assinatura, comite_gestor, consultoria_juridica, valor_estado, observacoes, area_encaminhamento, data_envio, proxima_providencia) VALUES
('024.00061740/2025-00', NULL, '2026-07-31', '2026-07-31', 'CAMPINAS', 'VII - Campinas', 'CRS', 'Instituição Padre Haroldo Rahm', 'Trata-se do Ofício PDC-348/2026 do Instituto Padre Haroldo, solicitando prorrogação do convênio nº 01571/2024, cuja vigência do 1º termo aditivo será até 30/09/2026 com reajuste de 5,5%, passando de R$ 2.835.000,00/ano para R$ 3.247.546,32/ano.', 'Termo Aditivo', 'Maristela', 'Análise da solicitação - GGCon', '2026-07-31', FALSE, FALSE, FALSE, NULL, NULL, NULL, NULL, NULL),
('024.00109165/2023-63', NULL, '2026-07-31', '2026-07-31', 'SÃO PAULO', 'I - Grande São Paulo', 'CRS', 'Grupo de Apoio ao Adolescente e a Criança com Câncer - GRAACC', 'Tratam os autos da prestação de contas apresentada pela Grupo de Apoio ao Adolescente e a Criança com Câncer - GRAACC, referente aos recursos repassados através ao Convênio Nº 290/2020, no valor R$ 100.000,00 (Cem mil reais), tendo por objeto: Custeio - Aquisição de Material de Consumo: Medicamentos.', 'Prestação de Contas', 'Marilsa', NULL, '2026-07-31', FALSE, FALSE, FALSE, NULL, NULL, NULL, NULL, NULL),
('024.00094070/2026-81', '127551', '2026-07-31', '2026-07-31', 'SÃO PAULO', 'I - Grande São Paulo', 'CRS', 'Fundação Oswaldo Ramos', 'Tratam os autos da prestação de contas apresentada pela Grupo de Apoio ao Adolescente e a Criança com Câncer - GRAACC, referente aos recursos repassados através ao Convênio Nº 290/2020, no valor R$ 100.000,00 (Cem mil reais), tendo por objeto: Custeio - Aquisição de Material de Consumo: Medicamentos.', 'Termo Aditivo', 'Arlete', 'Aguarda Formalização de Termo Aditivo', '2026-07-31', FALSE, FALSE, FALSE, NULL, NULL, NULL, NULL, NULL),
('024.00101577/2026-06', NULL, '2026-07-31', '2026-07-31', 'OSVALDO CRUZ', 'IX - Marília', 'CRS', 'Santa Casa de Misericórdia de OsvaLdo Cruz', 'Trata o presente expediente de Ofício Nº 20/2026, datado em 23/07/2026, do Diretor Administrativo da Santa Casa de Misericórdia de Osvaldo Cruz, solicitando antecipação na liberação de recursos financeiros já previstos para instalação do sistema de tratamento de ar (ar condicionado), no valor de R$ 512.000,00 (quinhentos e doze mil reais), parte integrante do Plano de Trabalho para funcionamento de 10 leitos de UTI na referida Instituição.', 'Convênio', 'Marta', 'Análise da solicitação - GGCon', '2026-07-31', FALSE, FALSE, FALSE, NULL, NULL, NULL, NULL, NULL),
('024.00038012/2025-96', '127318', '2026-08-03', '2026-08-03', 'BAURU', 'VI - Bauru', 'CRS', 'Prefeitura Municipal de Bauru', 'Tratam os autos da solicitação de continuidade do Programa Municipal de Nutrição e Suplementação Alimentar – PNSA, mediante transferência de recursos financeiros estaduais destinados à aquisição de leites especiais, suplementos alimentares, dietas e módulos nutricionais para atendimento de crianças e adolescentes residentes no Município de Bauru, em cumprimento à Ação Civil Pública nº 292/2002', 'Convênio', 'Fernanda', 'Aguardando a demanda ser cadastrada', '2026-08-03', FALSE, FALSE, FALSE, NULL, NULL, NULL, NULL, NULL),
('024.00032196/2025-81', NULL, '2026-08-03', '2026-08-03', 'FLÓRIDA PAULISTA', 'IX - Marília', 'CRS', 'IRMANDADE DA SANTA CASA DE MISERICÓRDIA DE FLORIDA PAULISTA', 'Tratam os autos da prestação de contas apresentada pela IRMANDADE DA SANTA CASA DE MISERICÓRDIA DE FLORIDA PAULISTA, referente aos recursos repassados através ao Convênio Nº 623/2024, no valor R$ 100.000,00 (Cem mil reais) tendo por objeto Custeio – Aquisição de Material de Consumo.', 'Prestação de Contas', 'Marilsa', 'Aguardando assinatura', '2026-08-03', TRUE, FALSE, FALSE, NULL, NULL, NULL, NULL, NULL),
('024.00086377/2025-27', NULL, '2026-08-03', NULL, 'ARIRANHA', 'XV - São José do Rio Preto', 'CRS', 'Prefeitura Municipal de Ariranha', 'Tratam os autos da prestação de contas apresentada pela Prefeitura Municipal de Ariranha, referente aos recursos repassados através ao Convênio Nº 384/2024, no valor R$ 300.00,00 (Trezentos mil reais), tendo por objeto de Custeio (Aquisição de Material de Consumo e Prestação de Serviços por Terceiros).', 'Prestação de Contas', 'Marilsa', 'Aguardando assinatura', '2026-08-03', TRUE, FALSE, FALSE, NULL, NULL, NULL, NULL, NULL),
('024.00021396/2024-27', NULL, '2026-08-03', NULL, 'MARÍLIA', 'IX - Marília', 'CRS', 'IRMANDADE DA SANTA CASA DE MISERICÓRDIA DE MARÍLIA', 'Tratam os autos da prestação de contas apresentada pela IRMANDADE DA SANTA CASA DE MISERICÓRDIA DE MARÍLIA-MAIS SANTA CASA, referente aos recursos repassados através ao Convênio Nº 836/2022, no valor R$ 5.313.103,68 (Cinco Milhões, Trezentos e treze mil, Cento e três reais, sessenta e oito centavos), tendo por objeto Custeio: Aquisição de material de Consumo.', 'Prestação de Contas', 'Marilsa', 'Aguardando assinatura', '2026-08-03', TRUE, FALSE, FALSE, NULL, NULL, NULL, NULL, NULL),
('024.00049290/2025-79', NULL, '2026-08-03', '2026-08-03', 'ARAÇATUBA', 'II - Araçatuba', 'CRS', 'SANTA CASA DE MISERICÓRDIA DE ARAÇATUBA', 'Trata-se do Ofício SC/ADM 78/2025 da Santa Casa de Araçatuba, datado de 24 de março de 2025, por meio do qual solicita recursos financeiros para investimento e custeio para a implantação da 10 leitos de UTI Pediátrica.', 'Convênio', 'Renata', 'Análise da solicitação - GGCon', '2026-08-03', FALSE, FALSE, FALSE, NULL, NULL, NULL, NULL, NULL),
('024.00092807/2026-21', '127638', '2026-08-03', '2026-08-03', 'ARAÇATUBA', 'II - Araçatuba', 'CRS', 'AMA – ASSOCIAÇÃO DE AMIGOS DO AUTISTA', 'Tratam os autos do recebimento do Ofício 098/2026 (0113451455) da AMA – ASSOCIAÇÃO DE AMIGOS DO AUTISTA, datado de 06/07/2026, o qual solicita Termo Aditivo ao Convênio nº 01517/2024, para manutenção dos repasses destinados a Custeio de atendimento a 110 (cento e dez) pacientes portadores de TEA, no valor total de R$ 2.779.378,80 (dois milhões, setecentos e setenta e nove mil, trezentos e setenta e oito reais e oitenta centavos), a serem pagos em 12 parcelas de R$ 231.614,90 (duzentos e trinta e um mil , seiscentos e quatorze reais e noventa centavos), prorrogando a vigência do Convênio até 05/08/2027.', 'Termo Aditivo', 'Renata', 'Aguarda Formalização de Termo Aditivo', '2026-08-03', FALSE, FALSE, FALSE, NULL, NULL, NULL, NULL, NULL),
('024.00016247/2025-27', NULL, '2026-08-04', '2026-08-04', 'SÃO PAULO', 'I - Grande São Paulo', 'CRS', 'Hospital das Clínicas da Faculdade de Medicina da Universidade de São Paulo HCFMUSP e Fundação Faculdade de Medicina - FFM', 'Trata o presente de prestação de contas do Convênio nº 000534/2023 - Exercício 2023 celebrado com o Hospital das Clínicas da Faculdade de Medicina da Universidade de São Paulo - HCFMUSP e Fundação Faculdade de Medicina - FFM.', 'Prestação de Contas', 'Marilsa', 'Aguardando assinatura', '2026-08-04', TRUE, FALSE, FALSE, NULL, NULL, NULL, NULL, NULL),
('024.00010790/2025-11', NULL, '2026-08-04', '2026-08-04', 'AVARÉ', 'VI - Bauru', 'CRS', 'Santa Casa de Misericórdia de Avaré', 'Tratam os autos da prestação de contas apresentada pela Santa Casa de Misericórdia de Avaré , referente aos recursos repassados através ao Convênio º 38/2022, no valor R$ 150.000,00 (cento e cinquenta mil reais ), tendo por objeto  custeio - material de consumo.', 'Prestação de Contas', 'Marilsa', 'Aguardando assinatura', '2026-08-04', TRUE, FALSE, FALSE, NULL, NULL, NULL, NULL, NULL),
('024.00056622/2025-71', NULL, '2026-08-04', NULL, 'Araraquara', 'III - Araraquara', 'CRS', 'Santa Casa de Misericórdia de Araraquara', 'Trata-se de processo de interesse da Irmandade da Santa Casa de Misericórdia de Araraquara que por meio do Ofício Provedoria nº 102/2026, de 29/05/2026 (0109853317), solicita apoio financeiro, com repasse em parcela única para a execução da obra do novo prédio do hospital com a implantação do ambulatório da oncologia – consultas, radiologia e quimioterapia, de 30 leitos de UTI- Adulto e de 68 leitos de enfermaria clínica e cirúrgica para cardiologia, ortopedia, neurologia, oncologia, oftalmologia e cirurgia endovascular, com o objetivo de ampliar os serviços assistenciais na alta complexidade aos pacientes do SUS no âmbito da RRAS-18 / DRS-III Araraquara.', 'Termo Aditivo', 'Tânia', 'Aguarda Formalização do Convênio', '2026-08-04', FALSE, FALSE, FALSE, NULL, NULL, NULL, NULL, NULL),
('024.00088743/2026-63', '126134', '2026-08-05', '2026-08-05', 'Campos do Jordão', 'XVII - Taubaté', 'CGGP', 'Sociedade Beneficente São Camilo - Hospital Leonor Mendes de Barros', 'Parecer Prévio do Comitê Gestor do Gasto Público - D. 126134 - Questionamento do Comitê Gestor', 'Convênio', 'Fernanda', 'Aguarda Deliberação do Comitê Gestor', '2026-08-05', FALSE, FALSE, FALSE, NULL, NULL, NULL, NULL, NULL),
('024.00092807/2026-21', NULL, '2026-08-05', '2026-08-05', 'ARAÇATUBA', 'II - Araçatuba', 'CRS', 'AMA – ASSOCIAÇÃO DE AMIGOS DO AUTISTA', 'SOLICITAÇÃO DE RENOVAÇÃO CONVÊNIO Nº1517/2024- AMA ARAÇATUBA.', 'Termo Aditivo', 'Renata', NULL, '2026-08-05', FALSE, FALSE, FALSE, NULL, NULL, NULL, NULL, NULL),
('024.00024214/2024-70', NULL, '2026-08-05', '2026-08-05', 'SÃO PAULO', 'I - Grande São Paulo', 'CCD', 'Fundação Faculdade de Medicina', 'proposta de formalização de convênio, com fundamento na Portaria GM/MS nº 2.342, de 13 de dezembro de 2023, que autoriza o repasse de recursos financeiros do Fundo Nacional de Saúde aos Fundos Estaduais de Saúde dos Estados gestores dos Serviços de Verificação de Óbito (SVO)- Capital.', 'Outros', 'Thiago', NULL, '2026-08-05', FALSE, FALSE, FALSE, NULL, NULL, NULL, NULL, NULL),
('024.00095068/2024-67', NULL, '2026-08-05', '2026-08-05', 'CAMPINAS', 'VII - Campinas', 'GS', 'Centro Infantil de Investigações Hematológicas Dr. Domingos A. Boldrini', 'solicitação para  renovação do convênio nº. 1547/2025, assinado em 29/08/2025, com validade até 28/09/2026 com a manutenção de repasse por um período de 12 meses e reajuste baseado na inflação de 4,11%, segundo (Boletim Focus do Banco Central), do Centro de Reabilitação Lucy Montoro', 'Termo Aditivo', 'Maristela', NULL, '2026-08-05', FALSE, FALSE, FALSE, NULL, NULL, NULL, NULL, NULL),
('024.00093233/2026-16', NULL, '2026-08-05', '2026-08-05', 'SÃO PAULO', 'I - Grande São Paulo', 'CGGP', 'Solicitação de Parecer Prévio - Demanda Lacan', 'solicita recursos financeiros no valor de $ 18.665.871,00 (dezoito milhões, seiscentos e sessenta e cinco mil e oitocentos e setenta e um reais) para manutenção dos repasses destinados a despesas com folha de pagamento, prestação de serviços e materiais de consumo e manutenção, para execução das atividades assistenciais médicas e não médicas no Hospital Lacan.', 'Convênio', 'Arlete', NULL, '2026-08-05', FALSE, FALSE, FALSE, NULL, NULL, NULL, NULL, NULL),
('024.00138145/2024-81', NULL, '2026-08-05', '2026-08-05', 'FRANCA', 'VIII - Franca', 'GPC', 'FUNDACAO SANTA CASA DE MISERICORDIA DE FRANCA', 'Tratam os autos da prestação de contas apresentada pela Fundação Santa Casa de Misericórdia de Franca, referente aos recursos repassados através ao Convênio º 495/2024, no valor R$ 300.000,00 (Trezentos mil reais), tendo por objeto Investimento.', 'Prestação de Contas', 'Marilsa', 'Aguardando análise técnica', '2026-08-05', FALSE, FALSE, FALSE, NULL, NULL, NULL, NULL, NULL),
('024.00133950/2023-37', NULL, '2026-08-05', '2026-08-05', 'BARRA BONITA', 'VI - Bauru', 'GPC', 'ASSOCIAÇÃO DO HOSPITAL E MATERNIDADE SÃO JOSÉ DE BARRA BONITA', 'eferente aos recursos repassados através ao Convênio º 422/2022, no valor R$ 100.000,00 (cem mil reais ), tendo por objeto Investimento - Aquisição de Equipamentos.', 'Prestação de Contas', 'Marilsa', 'Aguardando análise técnica', '2026-08-05', FALSE, FALSE, FALSE, NULL, NULL, NULL, NULL, NULL),
('024.00034359/2026-41', NULL, '2026-08-05', '2026-08-05', 'MOGI DAS CRUZES', 'I - Grande São Paulo', 'CRS', 'SPDM - Associação Paulista para Desenvolvimento da Medicina - Farmácia do Componente Especializado da Assistência Farmacêutica (CEAF) de Mogi das Cruzes', 'Respostas dos questionamentos da Consultoria Jurídica a cerca do Parecer CJ-SS 461/2026', 'Parecer/Consulta', 'Arlete', 'Encaminhar à Consultoria Jurídica', '2026-08-06', FALSE, FALSE, FALSE, NULL, NULL, NULL, NULL, NULL),
('024.00132654/2024-08', NULL, '2026-08-06', '2026-08-06', 'CHAVANTES', 'IX - Marília', 'CRS', 'Associação de Pais e Amigos dos Excepcionais de Chavantes-  APAE', 'Tratam os autos da prestação de contas apresentada pela Associação de Pais e Amigos dos Excepcionais de Chavantes-  APAE, referente aos recursos repassados através ao Convênio Nº 196/2021, no valor R$ 40.000,00 (Quarenta mil reais), tendo por objeto de Custeio - Material de Consumo.', 'Prestação de Contas', 'Marilsa', 'Aguardando assinatura', '2026-08-06', TRUE, FALSE, FALSE, NULL, NULL, NULL, NULL, NULL),
('024.00090524/2026-44', NULL, '2026-08-06', '2026-08-06', 'Campinas', 'VII - Campinas', 'CGOF', 'FUNDAÇÃO DA ÁREA DA SAÚDE DE CAMPINAS (FASCAMP)', 'Conforme consignado na Cota CJ/SS nº 458/2026, a Consultoria Jurídica concluiu pela aplicabilidade do Parecer Referencial CJ/SS nº 09/2026 ao caso concreto, determinando que a área técnica certifique a observância das orientações nele contidas, em especial aquelas constantes dos Capítulos VII e VIII.', 'Parecer/Consulta', 'Maristela', 'Aguardando Manifestação da àrea Técnica', '2026-08-06', FALSE, FALSE, FALSE, NULL, NULL, NULL, NULL, NULL),
('024.00114299/2024-87', NULL, '2026-08-06', '2026-08-06', 'NOVO HORIZONTE', 'XV - São José do Rio Preto', 'CRS', 'IRMANDADE SAO JOSE DE NOVO HORIZONTE', 'Tratam os autos da prestação de contas apresentada pela IRMANDADE SAO JOSE DE NOVO HORIZONTE, referente aos recursos repassados através ao Convênio nº 1263/2022, no valor R$ 300.000,00 (Trezentos mil reais), tendo por objeto custeio - material de consumo e prestação de serviços por terceiros.', 'Prestação de Contas', 'Marilsa', 'Aguardando assinatura', '2026-08-06', TRUE, FALSE, FALSE, NULL, NULL, NULL, NULL, NULL),
('024.00015571/2026-17', NULL, '2026-08-06', '2026-08-06', 'SÃO JOSÉ DO RIO PRETO', 'XV - São José do Rio Preto', 'CRS', 'FUNDAÇÃO FACULDADE REGIONAL DE MEDICINA DE SÃO JOSÉ DO RIO PRETO - FUNFARME', 'Tratam os autos da prestação de contas apresentada pela FUNDAÇÃO FACULDADE REGIONAL DE MEDICINA DE SÃO JOSÉ DO RIO PRETO - FUNFARME, referente aos recursos repassados através ao Convênio Nº 2005/2025- Exercício 2025, no valor R$ 149.999,92 (cento e quarenta e nove mil, novecentos e noventa e nove reais e noventa e dois centavos) tendo por objeto Custeio – Aquisição de material de consumo.', 'Prestação de Contas', 'Marilsa', 'Aguardando assinatura', '2026-08-06', TRUE, FALSE, FALSE, NULL, NULL, NULL, NULL, NULL),
('024.00016590/2025-71', NULL, '2026-08-06', '2026-08-06', 'FRANCA', 'VIII - Franca', 'CRS', 'FUNDACAO SANTA CASA DE MISERICORDIA DE FRANCA', 'Tratam os autos da prestação de contas apresentada pela FUNDACAO SANTA CASA DE MISERICORDIA DE FRANCA, referente aos recursos repassados através ao Convênio nº 1201/2024, no valor R$ 300.000,00 (Trezentos mil reais), tendo por objeto Custeio.', 'Prestação de Contas', 'Marilsa', 'Aguardando assinatura', '2026-08-06', TRUE, FALSE, FALSE, NULL, NULL, NULL, NULL, NULL),
('024.00217657/2024-11', NULL, '2026-08-06', '2026-08-06', 'BROTAS', 'VI - Bauru', 'CRS', 'Hospital Santa Therezinha de Brotas', 'Trata-se o presente da prestação de contas referente ao convênio nº 194/2023, entre a Secretaria da Saúde do Estado e a Fundação Doutor Amaral Carvalho, no valor total de R$ 150.000,00 (cem e cinquenta mil reais), Custeio', 'Prestação de Contas', 'Marilsa', 'Aguardando assinatura', '2026-08-06', TRUE, FALSE, FALSE, NULL, NULL, NULL, NULL, NULL),
('024.00056514/2026-80', NULL, '2026-08-06', '2026-08-06', 'SÃO PAULO', 'I - Grande São Paulo', 'CRS', 'Hospital da Clinicas da Faculdade de Medicina da Universidade de são Paulo', 'Tratam os autos da prestação de contas apresentada pelo Hospital da Clinicas da Faculdade de Medicina da Universidade de são Paulo, com a interveniência da Fundação Faculdade de Medicina , referente aos recursos repassados através do 1º. Primeiro Termo Aditivo ao Convênio Nº 537/2023, no valor R$ 26.319.315,48 (vinte e seis milhões, trezentos e dezenove mil, trezentos e quinze reais e quarenta e oito centavos), tendo por objeto custeio de folha de pagamento , material de consumo e prestação de serviços.', 'Prestação de Contas', 'Marilsa', 'Aguardando assinatura', '2026-08-06', TRUE, FALSE, FALSE, NULL, NULL, NULL, NULL, NULL),
('024.00018760/2025-52', NULL, '2026-08-07', NULL, 'Ribeirão Preto', 'XIII - Ribeirão Preto', 'GS', 'Prefeitura Municipal de Jaboticabal', NULL, 'Convênio', 'Fernanda', NULL, NULL, FALSE, FALSE, FALSE, NULL, NULL, NULL, NULL, NULL);
-- =============================================================================
-- Correções em movimentações já importadas (divergências entre o banco e a
-- planilha atual: acentuação corrompida na importação anterior + atualizações
-- reais de etapa/técnico/valor feitas na planilha desde então).
-- =============================================================================

UPDATE public.cgof_ggcon_processos SET processo_sei = '024.00013984/2023-14', numero_demanda = '17082', data_entrada = '2023-06-05', data_recebimento = NULL, municipio = 'São Paulo', drs_unidade = 'I - Grande São Paulo', coordenadoria = 'CRS', interessado = 'Santa Casa de Misericórdia de Santo Amaro - solicita prorrogação de vigência de pedido de Prorrogação do Convênio  nº 001340/2022 – Demanda nº 017082,  valor de R$ 300.000,00, Emenda Parlamentar, de 30/06/23, para 31/12/23', assunto = 'demanda não formalizada - Trata o presente de e-mail datado de 24 de Maio de 2023, da Santa Casa de Misericórdia de Santo Amaro, solicitando prorrogação do convênio nº 001340/2022 - Emenda:  2021.161.25499 - Demanda nº 17082 - R$ 300.000,00 (Trezentos Mil Reais).
                               Considerando o encerramento do Exercício de 2021, estamos aguardando liberação de recurso no exercício de 2023 para prosseguimento com a formalização do convênio e, devido a este fato não é possível atendermos a esse pleito.', tipo = 'Termo Aditivo', tecnico_responsavel = 'Jomara', etapa = 'Em trâmite', data_movimentacao = '2023-06-05', aguardando_assinatura = FALSE, comite_gestor = FALSE, consultoria_juridica = FALSE, valor_estado = NULL, observacoes = NULL, area_encaminhamento = NULL, data_envio = NULL, proxima_providencia = NULL WHERE codigo = 21; -- 024.00013984/2023-14
UPDATE public.cgof_ggcon_processos SET processo_sei = '024.00031022/2023-39', numero_demanda = '32410', data_entrada = '2023-06-19', data_recebimento = NULL, municipio = 'São Paulo', drs_unidade = 'I - Grande São Paulo', coordenadoria = 'CRS', interessado = 'Associação de Assistência à Criança Deficiente AACD - Gerente de Projetos e Estratégia Sandra Rodrigues', assunto = 'Trata o presente Processo de Ofício AACD nº 203/2023, da Gerente de Projetos e Estratégia Sandra Rodrigues, da AACD - Associação de Assistência à Criança Deficiente, que solicita a formalização da demanda nº 32410, emenda nº 2022.046.37971, Processo SES-PRC-2022-00610-DM, no valor de R$ 100.000,00 (cem mil reais), para aquisição de 08 (Oito), colchões de viscoelástico e redistribuição de peso e 02 (Dois), monitores de nível de sedação e relaxamento muscular.', tipo = 'Convênio', tecnico_responsavel = 'Jomara', etapa = 'Aguardando Andamento', data_movimentacao = '2023-06-19', aguardando_assinatura = FALSE, comite_gestor = FALSE, consultoria_juridica = FALSE, valor_estado = NULL, observacoes = NULL, area_encaminhamento = NULL, data_envio = NULL, proxima_providencia = NULL WHERE codigo = 50; -- 024.00031022/2023-39
UPDATE public.cgof_ggcon_processos SET processo_sei = '024.00147228/2023-80', numero_demanda = NULL, data_entrada = '2023-12-18', data_recebimento = NULL, municipio = 'Campinas', drs_unidade = 'VII - Campinas', coordenadoria = 'CGOF', interessado = 'Universidade Estadual de Campinas - UNICAMP', assunto = 'Solicitação de prorrogação de vigência do Convênio nº 757/2022, devido a fracasso de pregão', tipo = 'Termo Aditivo', tecnico_responsavel = NULL, etapa = 'devolvido drs', data_movimentacao = '2023-09-06', aguardando_assinatura = FALSE, comite_gestor = FALSE, consultoria_juridica = FALSE, valor_estado = NULL, observacoes = NULL, area_encaminhamento = NULL, data_envio = NULL, proxima_providencia = NULL WHERE codigo = 410; -- 024.00147228/2023-80
UPDATE public.cgof_ggcon_processos SET processo_sei = '024.00198672/2024-44', numero_demanda = NULL, data_entrada = '2025-01-21', data_recebimento = '2025-01-21', municipio = 'Instrução', drs_unidade = 'VII - Campinas', coordenadoria = 'GS', interessado = 'Sociedade Campineira de Educação e Instrução', assunto = 'Solicita alteração plano de trabalho, formalizado com descrição diferente do desejado. Convênio  1450/2024 assinado em 8/10/24, repasse em 21/10/24', tipo = 'Convênio', tecnico_responsavel = NULL, etapa = 'Em análise GGCon', data_movimentacao = '2025-01-28', aguardando_assinatura = FALSE, comite_gestor = FALSE, consultoria_juridica = FALSE, valor_estado = NULL, observacoes = 'ver dia 29/1/25', area_encaminhamento = NULL, data_envio = NULL, proxima_providencia = NULL WHERE codigo = 1327; -- 024.00198672/2024-44
UPDATE public.cgof_ggcon_processos SET processo_sei = '024.00086667/2025-71', numero_demanda = '76154', data_entrada = '2025-07-14', data_recebimento = '2025-07-14', municipio = 'Marcelina', drs_unidade = 'I - Grande São Paulo', coordenadoria = 'CGGP', interessado = 'Casa de Saúde Santa Marcelina', assunto = 'Solicitação de recursos para Custeio de material de consumo, no valor de R$ 999.999,98, Demanda 76154, Processo SES-PRC-2025-00302-DM', tipo = 'Outros', tecnico_responsavel = NULL, etapa = 'Comitê Gestor', data_movimentacao = NULL, aguardando_assinatura = FALSE, comite_gestor = TRUE, consultoria_juridica = FALSE, valor_estado = NULL, observacoes = NULL, area_encaminhamento = NULL, data_envio = NULL, proxima_providencia = NULL WHERE codigo = 1680; -- 024.00086667/2025-71
UPDATE public.cgof_ggcon_processos SET processo_sei = '024.00043337/2026-71', numero_demanda = '124421', data_entrada = '2026-05-28', data_recebimento = '2026-05-28', municipio = 'Araçatuba', drs_unidade = 'II - Araçatuba', coordenadoria = 'CRS', interessado = 'Associação de Pais e Amigos dos Excepcionais de Araçatuba', assunto = 'Solicitação de Termo Aditivo ao Convênio nº 758/2025, para custeio de atendimento a 50 pacientes portadores de TEA, pelo período de 12 meses', tipo = 'Termo Aditivo', tecnico_responsavel = 'Renata', etapa = 'Concluído', data_movimentacao = '2026-08-04', aguardando_assinatura = FALSE, comite_gestor = FALSE, consultoria_juridica = FALSE, valor_estado = NULL, observacoes = 'demanda 124421', area_encaminhamento = NULL, data_envio = NULL, proxima_providencia = NULL WHERE codigo = 2657; -- 024.00043337/2026-71
UPDATE public.cgof_ggcon_processos SET processo_sei = '024.00038012/2025-96', numero_demanda = '127318', data_entrada = '2026-07-22', data_recebimento = '2026-07-22', municipio = 'Bauru', drs_unidade = 'VI - Bauru', coordenadoria = 'CRS', interessado = 'Prefeitura Municipal de Bauru', assunto = 'Tratam os autos da solicitação de continuidade do Programa Municipal de Nutrição e Suplementação Alimentar – PNSA, mediante transferência de recursos financeiros estaduais destinados à aquisição de leites especiais, suplementos alimentares, dietas e módulos nutricionais para atendimento de crianças e adolescentes residentes no Município de Bauru, em cumprimento à Ação Civil Pública nº 292/2002', tipo = 'Termo Aditivo', tecnico_responsavel = 'Fernanda', etapa = 'Aguardando a demanda ser cadastrada', data_movimentacao = '2026-07-22', aguardando_assinatura = FALSE, comite_gestor = FALSE, consultoria_juridica = FALSE, valor_estado = NULL, observacoes = NULL, area_encaminhamento = NULL, data_envio = NULL, proxima_providencia = NULL WHERE codigo = 2903; -- 024.00038012/2025-96
UPDATE public.cgof_ggcon_processos SET processo_sei = '145.00018620/2025-35', numero_demanda = NULL, data_entrada = '2026-07-30', data_recebimento = '2026-07-29', municipio = 'São Paulo', drs_unidade = 'I - Grande São Paulo', coordenadoria = 'CRS', interessado = 'Hospital das Clínicas da Faculdade de Medicina da Universidade de São Paulo – HCFMUSP', assunto = 'Trata-se de solicitação apresentada pelo Hospital das Clínicas da Faculdade de Medicina da Universidade de São Paulo – HCFMUSP, com a interveniência da Fundação Faculdade de Medicina – FFM, por meio do Ofício nº 172/2025-HCFMUSP-7611, visando ao repasse de recursos financeiros no valor de R$7.154.712,24 (sete milhões, cento e cinquenta e quatro mil, setecentos e doze reais e vinte e quatro centavos), destinados ao custeio dos serviços especializados de Extensão ao Atendimento de Pacientes (SEAP) HIV/Aids – Casa da AIDS.', tipo = 'Convênio', tecnico_responsavel = 'Arlete', etapa = 'Consultoria Jurídica', data_movimentacao = '2026-08-04', aguardando_assinatura = FALSE, comite_gestor = FALSE, consultoria_juridica = TRUE, valor_estado = 7154712.24, observacoes = NULL, area_encaminhamento = NULL, data_envio = NULL, proxima_providencia = NULL WHERE codigo = 2958; -- 145.00018620/2025-35
