-- =============================================================================
-- PARTE 53: "Servidores" — controle de publicações no DOE do Tribunal de
-- Contas (TCE) e requisições de documentos, com prazo de resposta e status
-- de entrega à CATC. Módulo novo, sem equivalente anterior no sistema.
--
-- Unifica as duas sub-planilhas originais ("PUBLICAÇÕES - DOE" e
-- "REQUISIÇÕES"), que têm exatamente as mesmas colunas, numa única tabela
-- distinguida pelo campo `tipo`.
--
-- Execute no SQL Editor do Supabase.
-- =============================================================================

CREATE TABLE IF NOT EXISTS public.cgof_gpc_servidores (
    codigo          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tipo            TEXT NOT NULL CHECK (tipo IN ('PUBLICACAO_DOE','REQUISICAO')),
    processo_tce    TEXT,              -- número/descrição do processo no TCE (formato livre)
    beneficiario    TEXT,              -- entidade/prefeitura
    drs             INTEGER,           -- mesma numeração 1–17 usada em cgof_gpc_processos.drs
    convenio        TEXT,
    qtde_volumes    INTEGER,
    prazo           DATE,              -- prazo de resposta/entrega — usado para alerta na UI
    exercicio       TEXT,
    responsavel     TEXT,
    situacao        TEXT,
    observacoes     TEXT,
    entrega_catc    TEXT,              -- status/data de entrega à CATC (texto livre, como na planilha)
    created_at      TIMESTAMPTZ DEFAULT NOW(),
    updated_at      TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_gpc_servidores_tipo  ON public.cgof_gpc_servidores(tipo);
CREATE INDEX IF NOT EXISTS idx_gpc_servidores_prazo ON public.cgof_gpc_servidores(prazo);
CREATE INDEX IF NOT EXISTS idx_gpc_servidores_drs   ON public.cgof_gpc_servidores(drs);

-- Mesmo padrão das demais tabelas GPC (autenticação customizada, não Supabase Auth —
-- ver parte_00_fix_gpc_rls.sql): RLS desativada, acesso liberado para anon/authenticated.
ALTER TABLE public.cgof_gpc_servidores DISABLE ROW LEVEL SECURITY;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.cgof_gpc_servidores TO anon, authenticated;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO anon, authenticated;

COMMENT ON TABLE public.cgof_gpc_servidores IS
  'Controle de publicações no DOE e requisições de documentos do Tribunal de Contas (TCE), com prazo de resposta e status de entrega à CATC.';
