-- =============================================================================
-- PARTE 64: GGCON — Análise Processo (conferência de Prestação de Contas)
-- Nova tela dedicada à conferência documental da prestação de contas, com base
-- nos checklists oficiais "Instruções 01/2024 (Entidades)" e "Prestação de
-- Contas – 1º Setor (Prefeituras)". Fluxo: um usuário com permissão de
-- liberação cadastra o despacho e libera para um analista → o analista
-- preenche o checklist em tela → conclui → o liberador encaminha o processo
-- para outra área (GPC/DRS/CJ/Comitê Gestor). Toda troca de analista
-- responsável fica registrada em cgof_ggcon_analise_historico.
-- O sistema usa autenticação customizada (não Supabase Auth JWT) — as requisições
-- chegam sempre como role 'anon', então RLS fica desabilitado nestas tabelas, igual
-- ao padrão já corrigido para as demais tabelas GGCON/GPC (ver parte_38_fix_ggcon_rls.sql).
-- Execute no SQL Editor do Supabase.
-- =============================================================================

-- ── Cabeçalho da análise (espelha o formulário "Despacho" dos checklists) ────

CREATE TABLE IF NOT EXISTS public.cgof_ggcon_analises (
    id                       INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    processo_sei             TEXT NOT NULL,
    convenio_numero          TEXT,
    cnpj                     TEXT,
    interessado              TEXT,
    objeto                   TEXT,
    custeio                  BOOLEAN NOT NULL DEFAULT FALSE,
    investimento             BOOLEAN NOT NULL DEFAULT FALSE,
    valor_repasse            NUMERIC(18,2),
    vigencia_inicio          DATE,
    vigencia_termino         DATE,
    vigencia_prorrogado_ate  DATE,
    termo_aditivo_numeros    TEXT[],
    termo_retirratificacao   BOOLEAN NOT NULL DEFAULT FALSE,
    resolucao_numero         TEXT,
    tipo_conveniada          TEXT NOT NULL CHECK (tipo_conveniada IN ('ENTIDADE', 'PREFEITURA')),
    municipio                TEXT,
    drs_unidade              TEXT,
    status                   TEXT NOT NULL DEFAULT 'AGUARDANDO_LIBERACAO'
                              CHECK (status IN ('AGUARDANDO_LIBERACAO', 'AGUARDANDO_ANALISE', 'EM_ANALISE', 'CONCLUIDA')),
    analista_atual           TEXT,
    liberado_por             TEXT,
    data_recebimento         DATE,
    data_liberacao           DATE,
    data_inicio_analise      DATE,
    data_analise             DATE,
    data_encaminhamento      DATE,
    area_encaminhamento      TEXT,
    observacoes              TEXT,
    created_by               TEXT,
    created_at               TIMESTAMPTZ DEFAULT NOW(),
    updated_at               TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_cgof_ggcon_analise_processo_sei ON public.cgof_ggcon_analises(processo_sei);
CREATE INDEX IF NOT EXISTS idx_cgof_ggcon_analise_status       ON public.cgof_ggcon_analises(status);
CREATE INDEX IF NOT EXISTS idx_cgof_ggcon_analise_analista     ON public.cgof_ggcon_analises(analista_atual);

ALTER TABLE public.cgof_ggcon_analises DISABLE ROW LEVEL SECURITY;

COMMENT ON TABLE public.cgof_ggcon_analises IS
  'Análise/conferência documental de prestação de contas no GGCON. Um registro por processo em conferência; o checklist de itens fica em cgof_ggcon_analise_itens e a troca de analista responsável em cgof_ggcon_analise_historico.';

-- ── Itens do checklist (uma linha por item, criados em bloco a partir do
-- template fixo de services/ggconAnaliseChecklists.ts no momento do cadastro) ─

CREATE TABLE IF NOT EXISTS public.cgof_ggcon_analise_itens (
    id              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    analise_id      INTEGER NOT NULL REFERENCES public.cgof_ggcon_analises(id) ON DELETE CASCADE,
    item_numero     INTEGER NOT NULL,
    item_descricao  TEXT NOT NULL,
    resposta        TEXT CHECK (resposta IN ('SIM', 'NAO', 'NAO_SE_APLICA')),
    documento_sei   TEXT,
    observacao      TEXT,
    updated_at      TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_cgof_ggcon_analise_itens_analise ON public.cgof_ggcon_analise_itens(analise_id);

ALTER TABLE public.cgof_ggcon_analise_itens DISABLE ROW LEVEL SECURITY;

-- ── Histórico de responsáveis e eventos de status ────────────────────────────

CREATE TABLE IF NOT EXISTS public.cgof_ggcon_analise_historico (
    id                   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    analise_id           INTEGER NOT NULL REFERENCES public.cgof_ggcon_analises(id) ON DELETE CASCADE,
    evento               TEXT NOT NULL CHECK (evento IN ('LIBERADA', 'REATRIBUIDA', 'INICIADA', 'CONCLUIDA', 'ENCAMINHADA')),
    analista_anterior    TEXT,
    analista_novo        TEXT,
    usuario_responsavel  TEXT,
    data_evento          TIMESTAMPTZ DEFAULT NOW(),
    observacao           TEXT
);

CREATE INDEX IF NOT EXISTS idx_cgof_ggcon_analise_historico_analise ON public.cgof_ggcon_analise_historico(analise_id);

ALTER TABLE public.cgof_ggcon_analise_historico DISABLE ROW LEVEL SECURITY;

-- ── Permissão de usuário: quem pode liberar processos para a fila de análise ─
-- (Administradores sempre podem liberar, independente desta flag — ver
-- types.ts podeLiberarAnalise())

ALTER TABLE public.users
  ADD COLUMN IF NOT EXISTS ggcon_libera_analise boolean NOT NULL DEFAULT false;

COMMENT ON COLUMN public.users.ggcon_libera_analise IS
  'Se true, o usuário pode liberar processos GGCON para a fila de Análise de Processo, escolhendo o analista responsável.';
