-- =============================================================================
-- PARTE 43: "Atividades Avulsas" — trabalho de técnico não ligado a um processo
-- (ex.: auxiliar outro setor numa análise, ajudar a elaborar um documento).
--
-- Diferente de cgof_gpc_produtividade / cgof_gpc_fluxo_tecnico, essa tabela NÃO
-- tem registro_id — o trabalho que ela registra não está amarrado a um processo
-- específico do GPC. Por isso é uma tabela própria, não uma extensão das
-- existentes (que exigem registro_id NOT NULL).
--
-- Execute no SQL Editor do Supabase.
-- =============================================================================

CREATE TABLE IF NOT EXISTS public.cgof_gpc_atividade_avulsa (
    codigo          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tecnico         TEXT NOT NULL,
    tipo            TEXT NOT NULL,
    descricao       TEXT NOT NULL,
    contexto        TEXT,              -- referência livre: setor/processo/entidade auxiliado
    horas           NUMERIC(6,2),      -- tempo dedicado, opcional
    data_atividade  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    registrado_por  TEXT,              -- quem cadastrou (pode ser diferente do técnico, ex.: coordenador)
    created_at      TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_gpc_ativ_avulsa_tecnico ON public.cgof_gpc_atividade_avulsa(tecnico);
CREATE INDEX IF NOT EXISTS idx_gpc_ativ_avulsa_data    ON public.cgof_gpc_atividade_avulsa(data_atividade);

-- Mesmo padrão das demais tabelas GPC (autenticação customizada, não Supabase Auth —
-- ver parte_38_fix_ggcon_rls.sql): RLS desativada, acesso liberado para anon/authenticated.
ALTER TABLE public.cgof_gpc_atividade_avulsa DISABLE ROW LEVEL SECURITY;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.cgof_gpc_atividade_avulsa TO anon, authenticated;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO anon, authenticated;

COMMENT ON TABLE public.cgof_gpc_atividade_avulsa IS
  'Registro de trabalho de um técnico GPC que não está ligado a um processo específico (ex.: auxílio a outro setor, elaboração de documento, reunião técnica, treinamento). Conta como produtividade na tela "Produtividade" (coluna/card "Outras Atividades").';
