-- =============================================================================
-- PARTE 35: Parcelas individuais de Parcelamento/Reparcelamento
-- Execute no SQL Editor do Supabase
-- =============================================================================

-- ─────────────────────────────────────────────────────────────────────────────
-- cgof_gpc_parcela  (controle de cada parcela individual de um parcelamento/
-- reparcelamento: vencimento, valor, status de pagamento)
-- ─────────────────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.cgof_gpc_parcela (
    codigo          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    parcelamento_id INTEGER NOT NULL REFERENCES public.cgof_gpc_parcelamento(codigo) ON DELETE CASCADE,
    numero          INTEGER NOT NULL,
    data_vencimento DATE,
    valor           NUMERIC(18,2),
    pago            BOOLEAN NOT NULL DEFAULT FALSE,
    data_pagamento  DATE,
    obs             TEXT
);

CREATE INDEX IF NOT EXISTS idx_cgof_gpc_parcela_parcelamento ON public.cgof_gpc_parcela(parcelamento_id);

ALTER TABLE public.cgof_gpc_parcela ENABLE ROW LEVEL SECURITY;

CREATE POLICY "authenticated can read cgof_gpc_parcela"  ON public.cgof_gpc_parcela FOR SELECT TO authenticated USING (true);
CREATE POLICY "authenticated can write cgof_gpc_parcela"  ON public.cgof_gpc_parcela FOR ALL    TO authenticated USING (true) WITH CHECK (true);
