-- ============================================================================
-- Migração: Fluxo Técnico e campos de produtividade
-- Adiciona:
--   1. Campo num_paginas na tabela cgof_gpc_recebidos
--   2. Tabela cgof_gpc_fluxo_tecnico para rastreamento detalhado do fluxo
-- ============================================================================

-- 1. Adicionar campo num_paginas à tabela de recebidos
ALTER TABLE cgof_gpc_recebidos
  ADD COLUMN IF NOT EXISTS num_paginas integer DEFAULT NULL;

COMMENT ON COLUMN cgof_gpc_recebidos.num_paginas IS
  'Número de páginas do processo — usado para calcular complexidade e justificar prazos de análise';

-- 2. Criar tabela de fluxo técnico
CREATE TABLE IF NOT EXISTS cgof_gpc_fluxo_tecnico (
  id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  registro_id     integer NOT NULL REFERENCES cgof_gpc_recebidos(codigo) ON DELETE CASCADE,
  tecnico         text,
  data_evento     timestamptz NOT NULL DEFAULT now(),
  posicao_id      integer REFERENCES cgof_gpc_posicao(codigo),
  movimento       text,
  acao            text,
  tempo_dias      integer,
  num_paginas_analise integer,
  obs             text,
  created_at      timestamptz NOT NULL DEFAULT now()
);

COMMENT ON TABLE cgof_gpc_fluxo_tecnico IS
  'Registro detalhado de cada etapa do fluxo técnico do processo — para medição de produtividade';

-- 3. Índices para performance
CREATE INDEX IF NOT EXISTS idx_fluxo_tecnico_registro
  ON cgof_gpc_fluxo_tecnico(registro_id);

CREATE INDEX IF NOT EXISTS idx_fluxo_tecnico_tecnico
  ON cgof_gpc_fluxo_tecnico(tecnico);

CREATE INDEX IF NOT EXISTS idx_fluxo_tecnico_data
  ON cgof_gpc_fluxo_tecnico(data_evento);

CREATE INDEX IF NOT EXISTS idx_fluxo_tecnico_acao
  ON cgof_gpc_fluxo_tecnico(acao);

-- 4. RLS (Row Level Security) — manter padrão do projeto
ALTER TABLE cgof_gpc_fluxo_tecnico ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Permitir acesso total a cgof_gpc_fluxo_tecnico"
  ON cgof_gpc_fluxo_tecnico
  FOR ALL
  USING (true)
  WITH CHECK (true);
