-- =============================================================================
-- PARTE 36: Novo setor GGCON — Controle de Entrada de Processos SEI
-- Modelo de dados baseado na planilha "produtividade_todos.xlsm", aba SEI.
-- Cada linha representa uma movimentação de um processo SEI (o mesmo
-- "Nº Processo SEI" pode ter várias linhas ao longo do tempo — nunca se
-- apaga uma movimentação anterior, só se cadastra uma nova).
-- Execute no SQL Editor do Supabase
-- =============================================================================

CREATE TABLE IF NOT EXISTS public.cgof_ggcon_processos (
    codigo                 INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    processo_sei           TEXT NOT NULL,
    numero_demanda         TEXT,
    data_entrada           DATE,
    data_recebimento       DATE,
    municipio              TEXT,
    drs_unidade            TEXT,
    coordenadoria           TEXT,
    interessado            TEXT,
    assunto                TEXT,
    tipo                   TEXT,
    tecnico_responsavel    TEXT,
    etapa                  TEXT,
    data_movimentacao      DATE,
    aguardando_assinatura  BOOLEAN NOT NULL DEFAULT FALSE,
    comite_gestor          BOOLEAN NOT NULL DEFAULT FALSE,
    consultoria_juridica   BOOLEAN NOT NULL DEFAULT FALSE,
    valor_estado           NUMERIC(18,2),
    observacoes            TEXT,
    area_encaminhamento    TEXT,
    data_envio             DATE,
    proxima_providencia    TEXT,
    created_at             TIMESTAMPTZ DEFAULT NOW(),
    updated_at             TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_cgof_ggcon_processo_sei    ON public.cgof_ggcon_processos(processo_sei);
CREATE INDEX IF NOT EXISTS idx_cgof_ggcon_tecnico         ON public.cgof_ggcon_processos(tecnico_responsavel);
CREATE INDEX IF NOT EXISTS idx_cgof_ggcon_etapa           ON public.cgof_ggcon_processos(etapa);
CREATE INDEX IF NOT EXISTS idx_cgof_ggcon_coordenadoria   ON public.cgof_ggcon_processos(coordenadoria);
CREATE INDEX IF NOT EXISTS idx_cgof_ggcon_data_mov        ON public.cgof_ggcon_processos(data_movimentacao);

ALTER TABLE public.cgof_ggcon_processos ENABLE ROW LEVEL SECURITY;

CREATE POLICY "authenticated can read cgof_ggcon_processos"  ON public.cgof_ggcon_processos FOR SELECT TO authenticated USING (true);
CREATE POLICY "authenticated can write cgof_ggcon_processos" ON public.cgof_ggcon_processos FOR ALL    TO authenticated USING (true) WITH CHECK (true);

COMMENT ON TABLE public.cgof_ggcon_processos IS
  'Controle de entrada e movimentação de processos SEI do setor GGCON. Cada registro é uma movimentação; o "registro atual" de um processo_sei é sempre o de maior codigo/data_movimentacao — não há flag manual "último registro", isso é calculado pela aplicação.';
